plugins {
    id 'application'
}

group = 'com.minesweeper'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    // Главный класс для запуска
    mainClassName = 'com.minesweeper.Main'
}

test {
    useJUnitPlatform()
}